### ISSUE TITLE
Issue 23.976 timecode - Add(1)

### ISSUE THREAD

**Issue by ndeshpande2022** [CrystalComputerCorp/smpte-timecode#36] opened 2023-05-24 02:36 UTC
Hi there,

I just wanted to report a minor issue with the 23.976 support. 

Original timecode object:
```
{
  dropFrame: true,
  frameRateDen: 1001,
  frameRateNum: 24000,
  frameRate: 23.98,
  hours: 10,
  minutes: 0,
  seconds: 0,
  frames: 6,
  frameCount: 862926
}
```

**Before adding 1 frame tc:** 
_10:00:00;06 (Frame Count: 862926)_
**Add 1 frame:**
_tc.add(1)_
**After tc:**
_09:59:51;07 (Frame Count: 862927)_

This seems off...

**Comment by m1tk4** [comment] 2023-05-24 02:48
Thanks for reporting this. To my knowledge, drop frame is only applicable to 29.97 and 59.94 - 23.976 is NDF. 

How did you initialize the object in your example?

**Comment by ndeshpande2022** [comment] 2023-05-24 02:53
We drop in the timecode, framerate, and dropframe option:

smpteTc(tc, frameRate, dropFrame);

e.g. smpteTc(10:00:00;06, 23.976, false);

It still sets the drop frame option to true by default.

**Comment by ndeshpande2022** [comment] 2023-05-24 02:55
https://github.com/OwnZones/smpte-timecode/blob/master/smpte-timecode.js

I think this fork may have fixed it. Just wanted to point it out just in case it's helpful.

Thanks again for all your great work.

**Comment by m1tk4** [comment] 2023-05-24 03:02
the ";" in your timecode string sets drop frame (as per the doc on the main page of the project). Can you try it as 10:00:00:06 instead?

**Comment by ndeshpande2022** [comment] 2023-05-24 03:16
I thought the same thing, but it doesn't seem to help. It still creates a timecode object with dropframe = true;

**Comment by m1tk4** [comment] 2023-05-24 03:18
can you attach a snippet of your code please?

**Comment by m1tk4** [comment] 2023-05-24 03:20
actually never mind - I see where the problem is. Thanks for reporting this, I'll get it fixed over the weekend.

**Comment by m1tk4** [comment] 2023-05-24 03:23
NOTE: https://github.com/CrystalComputerCorp/smpte-timecode/blob/master/smpte-timecode.js#L49 only needs to be set for 29.97, 59.94.

Also check if third parameter overrides derived dropFrame

**Comment by m1tk4** [comment] 2023-05-24 03:30
@ndeshpande2022 until then can you try as a workaround initializing the framerate as [24000,1001] ?

**Comment by ndeshpande2022** [comment] 2023-05-24 10:36
@m1tk4 it's not a huge rush, I just thought I would report it in case it helps anyone else. Thanks for being proactive and providing a workaround. Very much appreciated.

**Comment by ndeshpande2022** [comment] 2023-05-24 10:44
> NOTE: https://github.com/CrystalComputerCorp/smpte-timecode/blob/master/smpte-timecode.js#L49 only needs to be set for 29.97, 59.94.
> 
> Also check if third parameter overrides derived dropFrame

This looks exactly right.

**Comment by ndeshpande2022** [comment] 2023-06-30 11:50
@m1tk4 Any update on when this will be fixed? would you accept a PR?

**Comment by m1tk4** [comment] 2023-06-30 13:48
resolved in https://github.com/CrystalComputerCorp/smpte-timecode/commit/61b491457e0f6bd363334cbb38ad5157d91888e0

**Closed as completed by m1tk4** 2023-06-30 13:48 UTC

**Comment by m1tk4** [comment] 2023-06-30 15:16
> @m1tk4 Any update on when this will be fixed? would you accept a PR?

Sorry, fixed and pushed new version today.
